server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SFDB?useSSL=false
    username: root
    password: 1567
    driver-class-name: com.mysql.cj.jdbc.Driver
    
mybatis:
  mapper-locations=classpath*: mapper/*.xml

jpa:
  hibernate:
    ddl-auto: none
