server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SFDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1567
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.back.*.repository
  mapper-locations: classpath:mapper/*/*.xml

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:3000"
        allowed-methods: GET, POST, PUT, DELETE
        allowed-headers: "*"
        max-age: 3600