server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SFDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1567
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.back.*.repository
  mapper-locations: classpath:mapper/*/*.xml

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:3000"
        allowed-methods: GET, POST, PUT, DELETE
        allowed-headers: "*"
        max-age: 3600
        
# OAuth 클라이언트 정보 설정
  security:
    oauth2:
      client:
        registration:
          google:  # 예시로 Google OAuth2 설정
            client-id: 360256300731-odu5dfeupc2d32nnc4d9tmai3gdmkjms.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8000/user/login/google"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://accounts.google.com/o/oauth2/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub